### ISSUE TITLE
Syntax highlighting has stopped working

### ISSUE THREAD

**Issue by ghost** [almic/language-apidoc#1]
Recently restarted my computer, only to find that language-apidoc no longer highlights the components in apiDoc definitions. 

Now all comments are one color - gray.

![screen shot 2018-11-22 at 10 33 48 am](https://user-images.githubusercontent.com/25911384/48911903-26bd6a00-ee42-11e8-99f0-d557e93e7bd7.png)

**Comment by almic** [comment]
Sorry for coming so late, but what other packages do you have installed? I'm testing this again and I noticed that, for me at least, anything starting with an `@` in a comment block is now highlighted.

I think that it's possible Atom updated language definitions and it may have broken this library completely, otherwise both of us have interfering packages.

**Comment by almic** [comment]
Update: Seems that Atom has a new way of defining grammars, and I'm positive this is why certain languages are stealing back comment block control from apiDoc. Right now, this package works perfectly in PHP comments, and after double-checking the `language-php` does NOT use this new method yet.

So just sit tight until I update to the new format!

Edit: the `language-todo` [suffers from this, too](https://github.com/atom/language-todo/issues/82). Seems a short-term solution is for you to disable tree sitter parsers, but as they plan on making this default I'm still going to update this.

**Comment by almic** [comment]
Sorry this took so long to fix, blame Max.
